# bot/quiz_data.py

QUIZ_QUESTIONS = [
    # ==========================================
    # 🌿 BOTANIQUE & SCIENCE (30 Questions)
    # ==========================================
    {"question": "Quel est le principal composant psychoactif de la weed ?", "options": ["CBD", "THC", "CBG", "CBN"], "answer": 1, "category": "Science 🔬"},
    {"question": "Comment s'appellent les petits cristaux brillants sur les têtes qui contiennent les cannabinoïdes ?", "options": ["Les pollens", "Les pistils", "Les trichomes", "Les terpènes"], "answer": 2, "category": "Botanique 🌿"},
    {"question": "Quel terpène donne à la weed son odeur de citron/agrumes ?", "options": ["Myrcène", "Linalol", "Pinène", "Limonène"], "answer": 3, "category": "Botanique 🌿"},
    {"question": "Laquelle de ces variétés est réputée pour donner un effet 'High' et énergisant ?", "options": ["Indica", "Sativa", "Ruderalis", "Afghan"], "answer": 1, "category": "Botanique 🌿"},
    {"question": "Comment appelle-t-on une plante de weed qui développe à la fois des fleurs mâles et femelles ?", "options": ["Hermaphrodite", "Hybride", "Trisomique", "Androgyne"], "answer": 0, "category": "Botanique 🌿"},
    {"question": "Quel cannabinoïde est célèbre pour ses propriétés relaxantes sans effet psychotrope ?", "options": ["THC", "CBG", "CBD", "THCV"], "answer": 2, "category": "Science 🔬"},
    {"question": "Quelle variété pousse naturellement selon l'âge et non selon le cycle de lumière (Autofloraison) ?", "options": ["Sativa", "Indica", "Ruderalis", "Haze"], "answer": 2, "category": "Botanique 🌿"},
    {"question": "Combien d'heures de lumière par jour faut-il en général pour lancer la floraison en intérieur ?", "options": ["24h", "18h", "12h", "8h"], "answer": 2, "category": "Botanique 🌿"},
    {"question": "Quel terpène est responsable de l'odeur terreuse et musquée (très présent dans les Indica) ?", "options": ["Myrcène", "Limonène", "Caryophyllène", "Linalol"], "answer": 0, "category": "Science 🔬"},
    {"question": "Comment s'appelle le processus de chauffe qui active le THC (ex: avant de cuisiner un space cake) ?", "options": ["La fermentation", "La décarboxylation", "L'oxydation", "La sublimation"], "answer": 1, "category": "Science 🔬"},
    {"question": "Quel système du corps humain interagit directement avec le cannabis ?", "options": ["Le système endocannabinoïde", "Le système lymphatique", "Le système nerveux central", "Le système cardio-vasculaire"], "answer": 0, "category": "Science 🔬"},
    {"question": "Comment s'appelle la molécule produite par notre propre cerveau, surnommée la 'molécule du bonheur' ?", "options": ["La sérotonine", "L'anandamide", "La dopamine", "Le CBD naturel"], "answer": 1, "category": "Science 🔬"},
    {"question": "Quelle partie de la plante produit la majorité de la résine ?", "options": ["Les feuilles nourricières", "Les racines", "Les calices (fleurs)", "Les tiges"], "answer": 2, "category": "Botanique 🌿"},
    {"question": "Quel est le ratio lumière/nuit classique pour la phase de croissance d'une plante ?", "options": ["12/12", "18/6", "24/0", "10/14"], "answer": 1, "category": "Botanique 🌿"},
    {"question": "Quelle couleur prennent souvent les pistils quand la fleur arrive à maturité ?", "options": ["Ils restent blancs", "Ils deviennent bleus", "Ils deviennent ambrés/bruns", "Ils tombent"], "answer": 2, "category": "Botanique 🌿"},
    {"question": "Que signifie l'acronyme THC ?", "options": ["Tétrahydrocannabinol", "Tétracannabidiol", "Trihydrocannabinol", "Tétracannabinol Hexagonal"], "answer": 0, "category": "Science 🔬"},
    {"question": "Quel nutriment est indispensable en grande quantité pendant la phase de croissance (NPK) ?", "options": ["Phosphore (P)", "Potassium (K)", "Azote (N)", "Calcium"], "answer": 2, "category": "Botanique 🌿"},
    {"question": "Comment appelle-t-on l'extraction de résine réalisée avec de l'eau et de la glace ?", "options": ["BHO", "Rosin", "Ice-o-Lator", "Dry Sift"], "answer": 2, "category": "Science 🔬"},
    {"question": "Quel cannabinoïde est souvent associé à la dégradation du THC et favorise le sommeil ?", "options": ["CBG", "CBN", "THCV", "CBD"], "answer": 1, "category": "Science 🔬"},
    {"question": "Quel type d'extraction utilise une presse à chaud pour extraire la résine sans solvant ?", "options": ["Le Rosin", "Le BHO", "L'Ice-o-Lator", "Le Shatter"], "answer": 0, "category": "Science 🔬"},
    {"question": "Comment appelle-t-on les feuilles à une seule foliole qui poussent dans les têtes ?", "options": ["Les feuilles nourricières", "Les Sugar leaves (feuilles de sucre)", "Les cotylédons", "Les stipules"], "answer": 1, "category": "Botanique 🌿"},
    {"question": "Quel terpène, aussi présent dans la lavande, donne un effet floral et apaisant ?", "options": ["Pinène", "Myrcène", "Linalol", "Caryophyllène"], "answer": 2, "category": "Science 🔬"},
    {"question": "Quel terpène donne une odeur de poivre noir et d'épices ?", "options": ["Caryophyllène", "Limonène", "Humulène", "Terpinéol"], "answer": 0, "category": "Science 🔬"},
    {"question": "Que veut dire 'BHO' dans le monde des extractions ?", "options": ["Big Hash Oil", "Butane Hash Oil", "Basic Hemp Oil", "Burning Hot Oil"], "answer": 1, "category": "Science 🔬"},
    {"question": "En botanique, comment s'appellent les deux petites feuilles rondes qui sortent de la graine ?", "options": ["Les folioles", "Les cotylédons", "Les pistils", "Les stomates"], "answer": 1, "category": "Botanique 🌿"},
    {"question": "Quelle famille de cannabis est réputée pour ses feuilles larges et sa petite taille ?", "options": ["Sativa", "Ruderalis", "Indica", "Haze"], "answer": 2, "category": "Botanique 🌿"},
    {"question": "Quelle famille de cannabis est réputée pour ses feuilles fines et sa grande taille ?", "options": ["Indica", "Kush", "Ruderalis", "Sativa"], "answer": 3, "category": "Botanique 🌿"},
    {"question": "Quel cannabinoïde est surnommé 'la mère de tous les cannabinoïdes' car il est le précurseur des autres ?", "options": ["CBG", "CBD", "THC", "CBN"], "answer": 0, "category": "Science 🔬"},
    {"question": "Comment s'appelle l'étape où l'on rince les plantes à l'eau claire avant la récolte ?", "options": ["Le curing", "Le flushing (rinçage)", "Le trimming", "Le drying"], "answer": 1, "category": "Botanique 🌿"},
    {"question": "Comment s'appelle l'affinage de la weed en bocaux pour améliorer le goût ?", "options": ["Le flushing", "Le drying", "Le curing", "Le sweating"], "answer": 2, "category": "Botanique 🌿"},

    # ==========================================
    # 💨 CULTURE 420 & HISTOIRE (30 Questions)
    # ==========================================
    {"question": "D'où vient vraiment l'expression '420' ?", "options": ["Un code de la police", "Un groupe d'étudiants (les Waldos)", "Le nombre de cannabinoïdes", "L'anniversaire de Bob Marley"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Quel pays a été le TOUT PREMIER au monde à légaliser totalement la weed (production et vente) ?", "options": ["Pays-Bas", "Canada", "Uruguay", "États-Unis"], "answer": 2, "category": "Histoire 📜"},
    {"question": "Quelle ville européenne est célèbre pour ses 'Coffee Shops' ?", "options": ["Barcelone", "Berlin", "Copenhague", "Amsterdam"], "answer": 3, "category": "Culture 420 💨"},
    {"question": "Comment s'appelle la poudre résineuse récupérée au fond d'un grinder ?", "options": ["Le Shit", "Le Kief (ou Skuff)", "Le BHO", "Le Rosin"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Que célèbre-t-on le 10 juillet (710) dans la culture stoner ?", "options": ["L'anniversaire de Snoop Dogg", "La fête du Haschisch", "La fête des Extractions (OIL)", "La fin de la prohibition"], "answer": 2, "category": "Culture 420 💨"},
    {"question": "Comment appelle-t-on un joint roulé uniquement avec de la weed (sans tabac) aux USA ?", "options": ["Un spliff", "Un blunt", "Un joint", "Un zedou"], "answer": 2, "category": "Culture 420 💨"},
    {"question": "Comment appelle-t-on un joint roulé dans une feuille de cigare ?", "options": ["Un blunt", "Un spliff", "Un cône", "Un bang"], "answer": 0, "category": "Culture 420 💨"},
    {"question": "Comment appelle-t-on un joint qui contient à la fois de la weed et du tabac (surtout en Europe) ?", "options": ["Un joint", "Un blunt", "Un spliff", "Un banger"], "answer": 2, "category": "Culture 420 💨"},
    {"question": "Quel quartier libre de Copenhague (Danemark) est célèbre pour son marché du cannabis à ciel ouvert ?", "options": ["Christiania", "Red Light District", "Nimbin", "Camden Town"], "answer": 0, "category": "Culture 420 💨"},
    {"question": "De quelle région du monde provient historiquement le Haschisch (tradition de la résine) ?", "options": ["Amérique du Sud", "Asie centrale / Moyen-Orient", "Europe de l'Est", "Afrique du Sud"], "answer": 1, "category": "Histoire 📜"},
    {"question": "Quelle région du Maroc est mondialement connue pour sa production de shit ?", "options": ["Marrakech", "Le Rif (Ketama)", "Casablanca", "Agadir"], "answer": 1, "category": "Histoire 📜"},
    {"question": "Dans l'argot français, comment appelle-t-on couramment un morceau de shit acheté pour 10 euros ?", "options": ["Une plaquette", "Un dix balles", "Un demi", "Un kil"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Comment appelle-t-on la pipe à eau qui utilise une douille pour fumer ?", "options": ["Un vaporisateur", "Un bang (Bong)", "Un bubbler", "Un chicha"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Qu'est-ce qu'un 'Space Cake' ?", "options": ["Un gâteau en forme d'alien", "Un gâteau infusé au beurre de cannabis", "Une variété de weed très forte", "Un surnom pour le shit"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Quel État américain a été le premier (avec Washington) à légaliser la weed récréative en 2012 ?", "options": ["Californie", "Colorado", "New York", "Texas"], "answer": 1, "category": "Histoire 📜"},
    {"question": "Comment s'appelle le beurre infusé au cannabis utilisé en cuisine ?", "options": ["Le beurre d'Amsterdam", "Le beurre de Marrakech", "Le beurre de Ketama", "Le Cannabeurre"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Dans les années 30 aux USA, quel film de propagande diabolisait la weed ?", "options": ["Reefer Madness", "Devil's Harvest", "Marijuana Menace", "Weed of Doom"], "answer": 0, "category": "Histoire 📜"},
    {"question": "En quelle année le Canada a-t-il légalisé la weed au niveau fédéral ?", "options": ["2014", "2016", "2018", "2020"], "answer": 2, "category": "Histoire 📜"},
    {"question": "Comment s'appelle le petit carton qu'on roule pour faire le filtre d'un joint ?", "options": ["Le toncar", "Le tip", "La cale", "Toutes ces réponses"], "answer": 3, "category": "Culture 420 💨"},
    {"question": "Quel pays est souvent surnommé le 'grenier à weed' de l'Europe grâce à ses clubs sociaux ?", "options": ["L'Espagne", "La Suisse", "La France", "L'Italie"], "answer": 0, "category": "Culture 420 💨"},
    {"question": "Comment appelle-t-on le fait de fumer dans un endroit clos pour garder la fumée (comme une voiture) ?", "options": ["Un sous-marin (Hotbox)", "Un aquarium", "Un nuage", "Une serre"], "answer": 0, "category": "Culture 420 💨"},
    {"question": "Quel mot jamaïcain (rasta) est souvent utilisé pour désigner l'herbe ?", "options": ["Ganja", "Zaza", "Kush", "Beuh"], "answer": 0, "category": "Culture 420 💨"},
    {"question": "D'où vient la variété originelle 'Kush' ?", "options": ["De Californie", "Des montagnes de l'Hindu Kush (Afghanistan/Pakistan)", "D'Amsterdam", "Du Maroc"], "answer": 1, "category": "Histoire 📜"},
    {"question": "Quel est le nom de l'appareil qui permet de chauffer la weed sans la brûler ?", "options": ["Le bang", "Le vaporisateur", "Le dab rig", "Le bubbler"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Qu'est-ce que le 'Dabbing' ?", "options": ["Une danse", "Fumer de l'herbe pure", "Consommer une extraction de concentré sur un clou chauffé", "Rouler un joint très fin"], "answer": 2, "category": "Culture 420 💨"},
    {"question": "Quel terme désigne un shit de très haute qualité qui bulle quand on le chauffe ?", "options": ["Le pollen", "Le filtré (ou mousseux/bubbly)", "Le commercial", "L'afghan"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Dans l'argot français, que signifie 'Pilon' ?", "options": ["Un bang", "Un gros joint de shit", "Une plante", "Un pochon"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Comment appelle-t-on la fin du joint qui brûle les doigts ?", "options": ["Le mégot", "Le cul", "Le cul-de-joint (Roach)", "Le reste"], "answer": 2, "category": "Culture 420 💨"},
    {"question": "Qu'est-ce que la 'Pâte d'Afghan' ?", "options": ["Un plat culinaire", "Un shit noir, très mou et malléable", "Une variété de beuh", "Un outil pour nettoyer son bang"], "answer": 1, "category": "Culture 420 💨"},
    {"question": "Comment appelle-t-on la sensation d'avoir la bouche complètement sèche après avoir fumé ?", "options": ["La pâteuse", "Le désert", "La dalle", "Le bad trip"], "answer": 0, "category": "Culture 420 💨"},

    # ==========================================
    # 🎬 FILMS & SÉRIES (30 Questions)
    # ==========================================
    {"question": "Dans le film 'How High', avec quoi Silas et Jamal fertilisent-ils leur plant ?", "options": ["Des cendres de leur pote Ivory", "Du sang de chauve-souris", "De l'engrais radioactif", "De l'eau bénite"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Quel duo de comiques est célèbre pour ses films de stoners dans les années 70/80 ?", "options": ["Key & Peele", "Cheech & Chong", "Jay & Silent Bob", "Harold & Kumar"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Dans 'Pineapple Express' (Délire Express), quel acteur joue le rôle du dealer Saul Silver ?", "options": ["Seth Rogen", "Jonah Hill", "James Franco", "Danny McBride"], "answer": 2, "category": "Films & Séries 🎬"},
    {"question": "Comment s'appelle le personnage de 'The Big Lebowski', grand amateur de weed et de bowling ?", "options": ["Le Dude", "Le King", "Le Boss", "Le Chief"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Dans quelle série Walter White vend-il de la meth, mais où Jesse Pinkman préfère la weed ?", "options": ["Narcos", "Peaky Blinders", "Breaking Bad", "Weeds"], "answer": 2, "category": "Films & Séries 🎬"},
    {"question": "Dans le film 'Friday', qui joue le rôle de Smokey, le pote défoncé de Craig ?", "options": ["Ice Cube", "Chris Tucker", "Kevin Hart", "Snoop Dogg"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Quel rappeur joue le rôle principal aux côtés de Wiz Khalifa dans 'Mac & Devin Go to High School' ?", "options": ["Dr. Dre", "Eminem", "Snoop Dogg", "Kid Cudi"], "answer": 2, "category": "Films & Séries 🎬"},
    {"question": "Dans 'How High', à quelle prestigieuse université Silas et Jamal sont-ils acceptés ?", "options": ["Oxford", "Stanford", "Harvard", "Yale"], "answer": 2, "category": "Films & Séries 🎬"},
    {"question": "Comment s'appelle la série Netflix où Kathy Bates gère un dispensaire de weed ?", "options": ["Weeds", "Disjointed", "High Maintenance", "Family Guy"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Dans la série 'Weeds', comment s'appelle la mère de famille qui se met à vendre de la beuh ?", "options": ["Skyler White", "Nancy Botwin", "Ruth Whitefeather", "Fiona Gallagher"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Quel est le nom de la serviette qui fume de la weed dans South Park ?", "options": ["Servietsky (Towelie)", "Mr Hankey", "Garrison", "Smokey"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Dans 'Pineapple Express', quelle création architecturale de fumette Saul invente-t-il ?", "options": ["Le blunt tulipe", "Le joint en croix (Cross joint)", "Le bang à gravité", "Le parachute"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Dans 'Harold & Kumar chassent le burger', quel fast-food cherchent-ils désespérément ?", "options": ["McDonald's", "Taco Bell", "White Castle", "KFC"], "answer": 2, "category": "Films & Séries 🎬"},
    {"question": "Dans le film 'Scary Movie', quel tueur finit par fumer un énorme joint avec Shorty ?", "options": ["Jason", "Ghostface", "Freddy", "Chucky"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Quel personnage de dessin animé a pour meilleur pote un chien nommé Scooby-Doo et a toujours faim ?", "options": ["Fred", "Shaggy (Sammy)", "Homer", "Fry"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Dans la série 'Trailer Park Boys', quel personnage cultive d'immenses champs de weed ?", "options": ["Julian", "Bubbles", "Ricky", "Mr Lahey"], "answer": 2, "category": "Films & Séries 🎬"},
    {"question": "Quel est le titre du premier film de Cheech & Chong sorti en 1978 ?", "options": ["Up in Smoke", "Half Baked", "Friday", "High School"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Dans 'Half Baked' (Les Fumistes), pourquoi les potes vendent-ils de la weed ?", "options": ["Pour acheter une voiture", "Pour sortir leur pote de prison", "Pour payer le loyer", "Pour ouvrir un dispensaire"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Qui a co-écrit et joué le rôle principal dans le film 'Half Baked' ?", "options": ["Dave Chappelle", "Seth Rogen", "Adam Sandler", "Kevin Hart"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Dans le film 'Clerks' (et tout l'univers de Kevin Smith), quel duo de stoners squatte toujours devant l'épicerie 'Quick Stop' ?", "options": ["Jay & Silent Bob", "Cheech & Chong", "Harold & Kumar", "Wayne & Garth"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Dans 'Family Guy' (Les Griffin), Brian et Stewie chantent une chanson pour légaliser quoi ?", "options": ["L'alcool", "La weed ('A Bag of Weed')", "Les armes", "Le mariage"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Quel film culte de Larry Clark (1995) suit des ados skateurs new-yorkais qui fument et boivent toute la journée ?", "options": ["Kids", "La Haine", "Mid90s", "Lords of Dogtown"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Quel acteur incarne le dealer 'Dante', toujours torse nu, dans le film 'Grandma's Boy' ?", "options": ["Peter Dante", "Adam Sandler", "Jonah Hill", "Seth Rogen"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Quelle actrice joue la pote déjantée dans 'Broad City', une série très 420 friendly ?", "options": ["Amy Poehler", "Ilana Glazer", "Aubrey Plaza", "Sarah Silverman"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Dans 'Scary Movie 2', qui fume la plante mutante avant de se faire fumer par elle ?", "options": ["Shorty", "Ray", "Brenda", "Cindy"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Dans la série 'That '70s Show', comment est filmée la célèbre scène où les personnages fument en cercle ?", "options": ["En noir et blanc", "En caméra cachée", "La caméra pivote au centre sur 360°", "Avec un filtre vert"], "answer": 2, "category": "Films & Séries 🎬"},
    {"question": "Comment s'appelle l'épisode de la saison 1 de 'That '70s Show' où ils fument en cercle ?", "options": ["The Circle", "Pilot", "Garage Sale", "Stoned"], "answer": 2, "category": "Films & Séries 🎬"},
    {"question": "Quel acteur incarne Ted, l'ours en peluche qui fume au bang ?", "options": ["Seth MacFarlane", "Mark Wahlberg", "Mila Kunis", "Seth Rogen"], "answer": 0, "category": "Films & Séries 🎬"},
    {"question": "Dans le film 'Puff, Puff, Pass', quelle règle est d'or quand on fume en groupe ?", "options": ["Garder la fumée 10s", "Tirer deux taffes et faire tourner", "Ne jamais tousser", "Payer sa part"], "answer": 1, "category": "Films & Séries 🎬"},
    {"question": "Dans Les Simpson, quel est le nom du chauffeur de bus scolaire grand amateur de fumette et de rock ?", "options": ["Snake", "Otto Bus", "Moe", "Barney"], "answer": 1, "category": "Films & Séries 🎬"},

    # ==========================================
    # 🎵 RAP & MUSIQUE (30 Questions)
    # ==========================================
    {"question": "Quel rappeur a sorti sa propre marque d'accessoires fumeurs appelée 'G-Pen' ?", "options": ["50 Cent", "Wiz Khalifa", "Snoop Dogg", "Eminem"], "answer": 0, "category": "Musique 🎵"},
    {"question": "Quel groupe de rap américain a sorti le hit 'Hits from the Bong' ?", "options": ["Wu-Tang Clan", "Outkast", "Cypress Hill", "Mobb Deep"], "answer": 2, "category": "Musique 🎵"},
    {"question": "Dans la culture Reggae/Rasta, comment appelle-t-on la weed ?", "options": ["La Ganja", "La Mary Jane", "L'Herbe", "Toutes ces réponses"], "answer": 3, "category": "Musique 🎵"},
    {"question": "Quel rappeur français a popularisé l'expression 'Pute Pute Pute' avec d'immenses joints ?", "options": ["Booba", "Alkpote", "Kaaris", "Jul"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Qui a sorti l'album 'Rolling Papers' en 2011, devenu un classique pour fumer ?", "options": ["Snoop Dogg", "Curren$y", "Wiz Khalifa", "Kid Cudi"], "answer": 2, "category": "Musique 🎵"},
    {"question": "Quel artiste reggae est l'interprète légendaire de 'Legalize It' en 1976 ?", "options": ["Bob Marley", "Peter Tosh", "Jimmy Cliff", "Damian Marley"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel est le nom du premier album culte de Dr. Dre, sorti en 1992, nommé d'après une variété de weed ?", "options": ["The Chronic", "Doggystyle", "2001", "Kush"], "answer": 0, "category": "Musique 🎵"},
    {"question": "Qui chante le classique stoner 'Because I Got High' ?", "options": ["Snoop Dogg", "Afroman", "Redman", "Method Man"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel rappeur français chante le titre 'Palpal' où il parle de consommation de beuh ?", "options": ["Nekfeu", "Orelsan", "Lomepal", "Vald"], "answer": 2, "category": "Musique 🎵"},
    {"question": "Kid Cudi a sorti un morceau iconique sur la fumette qui s'appelle...", "options": ["Marijuana", "Day 'n' Nite", "Pursuit of Happiness", "Toutes ces réponses"], "answer": 3, "category": "Musique 🎵"},
    {"question": "Quel célèbre duo de rappeurs américains a joué dans le film 'How High' ?", "options": ["Dr. Dre & Snoop Dogg", "Method Man & Redman", "Outkast", "Mobb Deep"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quelle variété de weed a été créée et popularisée par Wiz Khalifa ?", "options": ["OG Kush", "Khalifa Kush", "Wiz Haze", "Taylor Gang Gelato"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel album légendaire de Bob Marley contient le titre 'Kaya', argot jamaïcain pour l'herbe ?", "options": ["Exodus", "Legend", "Kaya", "Catch a Fire"], "answer": 2, "category": "Musique 🎵"},
    {"question": "Quel rappeur de la Mafia K'1 Fry est connu pour son amour inconditionnel du haschisch ?", "options": ["Rohff", "Rim'K", "Kery James", "Mokobé"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel album légendaire de Doc Gynéco, sorti en 1996, est un classique pour les fumeurs français ?", "options": ["Première Consultation", "Quelques gouttes suffisent", "L'École du micro d'argent", "Mauvais œil"], "answer": 0, "category": "Musique 🎵"},
    {"question": "Comment s'appelle l'émission YouTube de Snoop Dogg où il fume avec ses invités ?", "options": ["Snoop's House", "GGN (Double G News)", "Smoke & Talk", "The Doggfather Show"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel groupe jamaïcain chante 'Pass the Dutchie' ?", "options": ["Bob Marley & The Wailers", "Musical Youth", "Inner Circle", "The Gladiators"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel rappeur américain a récemment déclaré (pour un coup de com) qu'il arrêtait de fumer ?", "options": ["Snoop Dogg", "Wiz Khalifa", "Post Malone", "B-Real"], "answer": 0, "category": "Musique 🎵"},
    {"question": "Quel chanteur français a écrit 'Le Poinçonneur des Lilas' et fuma souvent de la Gitane (et autres) ?", "options": ["Renaud", "Serge Gainsbourg", "Jacques Dutronc", "Alain Bashung"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Comment s'appelle le groupe de rap de B-Real et Sen Dog, pionniers de la culture weed ?", "options": ["Cypress Hill", "House of Pain", "Wu-Tang Clan", "Public Enemy"], "answer": 0, "category": "Musique 🎵"},
    {"question": "Quel est le titre du feat entre Snoop Dogg et Wiz Khalifa devenu l'hymne des stoners modernes ?", "options": ["Young, Wild & Free", "Kush Ups", "Smokin' On", "French Inhale"], "answer": 0, "category": "Musique 🎵"},
    {"question": "Quel rappeur a dit la célèbre phrase 'Smoke weed everyday' à la fin d'une musique de Dr. Dre ?", "options": ["Snoop Dogg", "Nate Dogg", "Eminem", "Kurupt"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel groupe de rap français des années 90 chantait 'Laisse pas traîner ton fils' et fumait du shit ?", "options": ["IAM", "NTM", "Secteur Ä", "Sniper"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel classique du groupe 113 parle de contrebande et commence par 'On est les princes de la ville' ?", "options": ["Tonton du Bled", "Les Princes de la ville", "Jackpotes 2000", "Ouais Gros"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel rappeur belge a sorti le morceau sombre et classique 'Amnésie' ?", "options": ["Caballero", "Roméo Elvis", "Damso", "Hamza"], "answer": 2, "category": "Musique 🎵"},
    {"question": "Quel est le vrai nom de la 'Mary Jane' chantée par Rick James ?", "options": ["Une femme", "La weed", "La cocaïne", "L'héroïne"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Quel groupe de rap originaire de Memphis est célèbre pour ses instrus planantes et son amour de la fumette ?", "options": ["Three 6 Mafia", "Outkast", "Migos", "Rae Sremmurd"], "answer": 0, "category": "Musique 🎵"},
    {"question": "Quel artiste reggae contemporain a chanté 'Welcome to Jamrock' ?", "options": ["Chronixx", "Damian Marley", "Stephen Marley", "Koffee"], "answer": 1, "category": "Musique 🎵"},
    {"question": "Dans quelle ville américaine le style G-Funk (fortement associé à la weed) est-il né ?", "options": ["New York", "Atlanta", "Los Angeles (Compton/Long Beach)", "Chicago"], "answer": 2, "category": "Musique 🎵"},
    {"question": "Quel rappeur a sorti sa propre marque de beuh appelée 'Trees by Game' ?", "options": ["The Game", "Rick Ross", "Lil Wayne", "2 Chainz"], "answer": 0, "category": "Musique 🎵"},

    # ==========================================
    # 🎮 JEUX VIDÉOS & INTERNET (30 Questions)
    # ==========================================
    {"question": "Dans GTA San Andreas, quel personnage te fait faire des missions en fumant constamment ?", "options": ["Big Smoke", "Ryder", "Sweet", "The Truth"], "answer": 3, "category": "Jeux Vidéos 🎮"},
    {"question": "Quel est le nom du Pokémon Plante souvent associé à la weed sur internet ?", "options": ["Boustiflor", "Bulbizarre", "Mystherbe", "Florizarre"], "answer": 2, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans Minecraft, quelle est l'utilité des cisailles sur des feuilles d'arbre ?", "options": ["Faire du shit", "Récupérer le bloc de feuilles", "Couper du bois", "Rien"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans Far Cry 3, sur quelle musique doit-on brûler des champs de weed au lance-flammes ?", "options": ["Skrillex - Make It Bun Dem", "Bob Marley - Fire", "Snoop Dogg - Drop It Like It's Hot", "Prodigy - Firestarter"], "answer": 0, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans League of Legends, comment s'appelle le champion qui est un arbre géant ?", "options": ["Ivern", "Maokai", "Groot", "Sylas"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Quel rappeur/streamer est resté mute pendant 45 minutes sur Twitch en fumant avant de s'en rendre compte ?", "options": ["Post Malone", "T-Pain", "Snoop Dogg", "Soulja Boy"], "answer": 2, "category": "Internet 🌐"},
    {"question": "Dans GTA V, qui est le pote de Franklin qui gère un business de beuh (LD Organics) ?", "options": ["Trevor", "Lamar Davis", "Michael", "Jimmy"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Comment s'appelle le meme du gars au visage très rouge, l'air complètement défoncé ?", "options": ["10 Guy (Stoner Stanley)", "Bad Luck Brian", "Pepe the Frog", "Doge"], "answer": 0, "category": "Internet 🌐"},
    {"question": "Dans le jeu 'Weedcraft Inc', quel est le but principal ?", "options": ["Fumer le plus possible", "Gérer un empire de production et de vente de weed", "Échapper à la police dans la forêt", "Créer des bangs en verre"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans GTA San Andreas, que cache The Truth dans sa ferme ?", "options": ["Des aliens", "Des champs de weed géants", "Des armes nucléaires", "Des voitures volées"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Sur Twitch, quelle catégorie est souvent utilisée pour les streams 'chill & fumette' ?", "options": ["Just Chatting", "Art", "Science & Technology", "ASMR"], "answer": 0, "category": "Internet 🌐"},
    {"question": "Dans le jeu narratif 'Life is Strange', quel personnage rebelle peut-on voir fumer de la beuh dans sa chambre ?", "options": ["Max Caulfield", "Chloe Price", "Rachel Amber", "Warren"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Quel rappeur/streameur américain est devenu un meme à cause de sa manette Xbox cassée en live et de sa fumette sur Twitch ?", "options": ["Soulja Boy", "Snoop Dogg", "Post Malone", "T-Pain"], "answer": 1, "category": "Internet 🌐"},
    {"question": "Dans quel jeu de gestion de prison peux-tu fouiller les cellules pour trouver de la contrebande, dont des drogues ?", "options": ["Prison Architect", "The Escapists", "RimWorld", "SimCity"], "answer": 0, "category": "Jeux Vidéos 🎮"},
    {"question": "Quelle entreprise de jeux vidéo a créé le jeu culte de skate 'Skate 3', parfait pour jouer défoncé ?", "options": ["Ubisoft", "Rockstar", "EA (Electronic Arts)", "Activision"], "answer": 2, "category": "Jeux Vidéos 🎮"},
    {"question": "Comment s'appelle le personnage principal du jeu 'High on Life', créé par le co-créateur de Rick et Morty ?", "options": ["Il n'a pas de nom (Bounty Hunter)", "Morty", "Kenny", "Lefty"], "answer": 0, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans 'Animal Crossing', quel personnage a les yeux toujours mi-clos et ressemble à un stoner ?", "options": ["Tom Nook", "Pascal la loutre", "Kéké Laglisse", "Marie"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans 'Cyberpunk 2077', peut-on trouver et fumer de la drogue de synthèse ?", "options": ["Oui, c'est très commun", "Non, c'est interdit par le jeu", "Seulement dans une mission", "Uniquement de l'alcool"], "answer": 0, "category": "Jeux Vidéos 🎮"},
    {"question": "Quel réseau social a longtemps censuré massivement les comptes liés à la culture 420 (avant de s'assouplir) ?", "options": ["Twitter (X)", "Instagram", "Reddit", "Tumblr"], "answer": 1, "category": "Internet 🌐"},
    {"question": "Que signifie MLG dans les fameux montages vidéos internet remplis de weed, de Doritos et de Snoop Dogg ?", "options": ["Major League Gaming", "Mega Loud Ganja", "Much Love Guys", "My Little Ganja"], "answer": 0, "category": "Internet 🌐"},
    {"question": "Quel objet du jeu 'Mario Kart' est souvent détourné en blague stoner à cause de son aspect (champignon) ?", "options": ["La fleur de feu", "L'étoile", "Le champignon (Toad)", "La carapace bleue"], "answer": 2, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans 'The Last of Us Part II', que trouvent Ellie et Dina dans le sous-sol de la bibliothèque ?", "options": ["Des armes", "Un vieux bocal de weed", "Un infecté", "Une radio"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Quel meme internet met en scène une grenouille souvent associée aux 'Doomers' et à la fumette solitaire ?", "options": ["Pepe the Frog", "Dat Boi", "Kermit", "Crazy Frog"], "answer": 0, "category": "Internet 🌐"},
    {"question": "Dans le jeu 'Disco Elysium', quelle substance illicite le détective peut-il consommer pour booster son intelligence ?", "options": ["Du Speed", "Du Pyrholidon", "Du Nosaphed", "Toutes ces réponses"], "answer": 3, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans 'Rust', quelle plante cultivable est un des piliers de l'économie entre joueurs ?", "options": ["Le blé", "La citrouille", "Le chanvre (Cloth)", "Le maïs"], "answer": 2, "category": "Jeux Vidéos 🎮"},
    {"question": "Quel jeu indépendant primé te permet de gérer une ferme de A à Z (idéal pour chiller) ?", "options": ["Stardew Valley", "Terraria", "Hollow Knight", "Celeste"], "answer": 0, "category": "Jeux Vidéos 🎮"},
    {"question": "Dans 'Garry's Mod', quel mode de jeu RP implique souvent des cultivateurs de weed cachés dans des apparts ?", "options": ["Prop Hunt", "DarkRP", "Trouble in Terrorist Town", "Deathrun"], "answer": 1, "category": "Jeux Vidéos 🎮"},
    {"question": "Sur quel forum internet la culture stoner a-t-elle explosé dans les années 2000 avec le fameux board /trees ?", "options": ["4chan", "Reddit", "Digg", "9gag"], "answer": 1, "category": "Internet 🌐"},
    {"question": "Quel jeu de plateforme psychédélique met en scène un héros sans membres, parfait à faire défoncé ?", "options": ["Rayman", "Crash Bandicoot", "Spyro", "Sonic"], "answer": 0, "category": "Jeux Vidéos 🎮"},
    {"question": "Comment s'appelle l'application de livraison de bouffe (très utilisée en cas de foncedalle) ?", "options": ["Uber Eats", "WeedEats", "HighDelivery", "MunchiesApp"], "answer": 0, "category": "Internet 🌐"},
]